"""empty message

Revision ID: fac4165c4a97
Revises: 2ad561794500
Create Date: 2025-08-10 14:31:33.035552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fac4165c4a97'
down_revision = '2ad561794500'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'character_id')
    )
    op.drop_table('favorite_characters')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_characters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name='favorite_characters_character_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='favorite_characters_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorite_characters_pkey')
    )
    op.drop_table('favorites')
    # ### end Alembic commands ###
